# Generated by Django 5.2 on 2025-05-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_userprofile_birth_date_userprofile_is_online_and_more"),
    ]

    operations = []
